name: write

on:
  workflow_dispatch:
  schedule:
    - cron: '35 8,13,17,20 * * 1-6'
  watch:
    types: [started]

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Export secrets to env
        shell: bash
        run: |
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

          # 導出多帳號配置的 JSON（必填）
          echo "ACCOUNTS_JSON<<EOF" >> $GITHUB_ENV
          echo '${{ secrets.ACCOUNTS_JSON }}' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run
        shell: bash
        run: |
          set -e
          cd src
          dotnet run Program.cs write
