name: write

on:
  workflow_dispatch:
  schedule:
    # This ensures tokens are refreshed before expiration (typically 90 days)
    - cron: '35 8,13,17,20 * * 1-6'
  # watch:
  #   types: [started]

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository to access source code
      - name: Checkout
        uses: actions/checkout@v3

      # Install .NET 10 SDK for C# script execution
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      # Execute write operations against Microsoft Graph API
      # This mode performs create/update/delete operations
      # - IMPORTANT: Automatically cleans up all created resources after operations
      #   to avoid leaving test artifacts in the account
      - name: Execute Write Operations with Auto-Cleanup
        shell: bash
        env:
          # JSON configuration containing multiple Microsoft accounts
          # Format: [{"ClientId":"...", "ClientSecret":"...", "RefreshToken":"..."}]
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        run: |
          cd src
          dotnet run Program.cs write
